name: Code Check
on: [push]

jobs:
  build:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CPP Check
        uses: deep5050/cppcheck-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
      - name: Flaw Finder
        uses: deep5050/flawfinder-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
