name: macOS Binary
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Boost
      run: brew install boost
    - name: Test Vina
      run: cd build/mac/release && ./vina --version
