name: macOS Binary
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Boost
      run: brew install boost@1.72 makedepend
    - name: Build Vina and Vina Split
      run: cd build/mac/release && make depend && make vina && ./vina --version
    - name: Upload vina
      uses: actions/upload-artifact@v1
      with:
        name: vina
        path: ./build/mac/release/vina

