name: Ubuntu Binary
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install g++
      run: sudo apt-get install g++ xutils-dev
    - name: Install Boost 1.74
      run: brew install navanchauhan/homebrew-tap/boost-for-vina
    - name: Build Vina and Vina_Split
      run: cd build/linux/release && make depend && make all && ./vina --version
    - name: Upload vina
      uses: actions/upload-artifact@v1
      with:
        name: vina
        path: ./build/linux/release/vina
    - name: Upload Vina_Split
      uses: actions/upload-artifact@v1
      with:
        name: vina_split
        path: ./build/linux/release/vina_split