name: Ubuntu Binary
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install g++
      run: sudo apt-get install g++ xutils-dev
    - name: Install Boost 1.72
      run: brew install boost@1.72
    - name: Build Vina and Vina Split
      run: cd build/linux/release && make depend && make all && ./vina --version
